Herman\WebAppTestBundle\Entity\Country:
    type: entity
    table: countries
    repositoryClass: Herman\WebAppTestBundle\Entity\CountryRepository
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 250
            fixed: false
            nullable: true
    lifecycleCallbacks: {  }
