parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: webapptest
    database_user: root
    database_password: hcadbadmin
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: ef1155573f2cceaea27bd9d116e586d1b1836b22
    database_path: null
